kind: pipeline
name: default

steps:
- name: test
  image: rust:1.62
  commands:
  - rustup component add rustfmt
  - cargo check --verbose --all
  - cargo fmt --check --verbose --all
  - cargo test --verbose --all
